version: '3'
services:
  dns.service:
    restart: always
    container_name: sftp
    privileged: true
    image: "sftp:latest"
    build: .
    volumes:
      - ${HOME}/Documents/git/sftp:/go/src/sftp
      - ${HOME}/Documents/git/sftp/data/users:/data/users
      - ${HOME}/Documents/git/sftp/data/public:/data/public
      - ${HOME}/Documents/git/sftp/data/cache:/data/users_cache
    ports:
      - "24:22"
      - "5000:8081"