version: '3.2'
services:
  sftp.service:
    restart: always
    container_name: sftp
    privileged: true
    image: "sftp:latest"
    build: .
    volumes:
      - type: bind
        source: /c/Users/SUPRASUMO/Documents/git/sftp 
        target: /go/src/sftp
      - type: bind
        source: /c/data/users
        target: /data/users
      - type: bind
        source: /c/data/public
        target: /data/public
      - type: bind
        source: /c/data/cache
        target: /data/users_cache   
    ports:
      - "24:22"
      - "5000:8081"