version: '3.2'
services:
  sftp.service:
    restart: always
    container_name: sftp
    privileged: true
    image: "sftp:latest"
    build: .
    volumes:
      - type: bind
        source: ~/git/sftp
        target: /go/src/sftp
      - type: bind
        source: /data/users
        target: /data/users
        #- type: bind
        #source: /media/Data
        #target: /data/public
      - type: bind
        source: /data/cache
        target: /data/users_cache
    ports:
      - "24:22"
      - "5000:8081"
